### ISSUE TITLE
angular 2 integration

### ISSUE THREAD

**Issue by lilling** [richbl/ng2-bootstrap-visualizejs#7]
Hey there!
I see you didnt update your repo for quite some time.
We are looking for scalable reporting machnism that would work in angular 2 application.
do you have a solution for us?
thanks.

**Comment by richbl** [comment]
@lilling, the repository is currently running against Angular 2.0, and there appear to be no known issues. 

Are you interested in using the Jaspersoft Visualize JS library specifically (demonstrated here)? Put differently, what are your requirements?

Rich
